import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const PORT = process.env.PORT || 3000;
export const POLL_INTERVAL = process.env.POLL_INTERVAL 
  ? parseInt(process.env.POLL_INTERVAL, 10) 
  : 10 * 60 * 1000; // 10 minutes default

export const FEEDS_DB_PATH = process.env.FEEDS_DB_PATH || path.join(__dirname, 'data', 'feeds.json');
export const WEBHOOKS_DB_PATH = process.env.WEBHOOKS_DB_PATH || path.join(__dirname, 'data', 'webhooks.json');

export const MAX_FEED_ITEMS = process.env.MAX_FEED_ITEMS 
  ? parseInt(process.env.MAX_FEED_ITEMS, 10) 
  : 100;

export const FEED_TITLE = process.env.FEED_TITLE || 'Aggregated RSS Feed';
export const FEED_DESCRIPTION = process.env.FEED_DESCRIPTION || 'Unified feed generated by RSS Generator Server';
export const FEED_LINK = process.env.FEED_LINK || `http://localhost:${PORT}/feed`;
